[package]
name = "actix-rust-template"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
mimalloc = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
